apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: ${PROM_USER}
    secureJsonData:
      basicAuthPassword: ${PROM_PASS}
    isDefault: true
    editable: true
